---
title: "Vignette Title"
author: "Vignette Author"
date: "`r format(Sys.Date() '%m/%d/%Y')`"
abstract: >
    When working with omics data you will encounter technical biases. These can often in part be remedied by using appropriate normalization approach. Normalyzer helps this process by both performing a number of readibly available normalizations as well as generating a summary document of the results.
    NormalyzerDE package version: `r packageVersion("NormalyzerDE")`
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Differential expression and countering technical biases using NormalyzerDE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, results="hide"}
# knitr::opts_chunk$set(tidy=FALSE, cache=TRUE, dev="png", message=FALSE,
# error=FALSE, warning=TRUE)
```

# Default use

Mention citing.

## Input format

NormalyzerDE expects a raw data file in the following format:

```
Example of format
```

Furthermore, it expects a design matrix:

```
Example of design matrix
```

The data matrix can be replaced with the output matrix from Proteios or peptide or protein (names?) output from MaxQuant.

Finally, it is possible to process using the format used in Normalyzer. There, no design matrix was used and sample groups were instead specified by adding an extra row at the top of the matrix.

```
Example of old format
```

## Processing

## Evaluating results

# Retention time normalization

Retention time based normalization can be performed with an arbitrary normalization matrix.

## Basic usage

## Defining a wrapper

# Stepwise processing

NormalyzerDE consists of a set of steps. You can influence the order of this processing using options (X and X), but they can also be called directly from R.

## Data formats


